### PR TITLE
Update ogr2ogr version

### PR DESCRIPTION
**Pull request by macrouch**

### CODE REVIEW

**Comment by macrouch** [comment]
Node 12 tests failed, but that went end of life last year. Do you still want to support it?

**Comment by wavded** [comment]
Thx @macrouch! We can remove Node v12 support, can you update?

**Comment by macrouch** [comment]
> Thx @macrouch! We can remove Node v12 support, can you update?

Yep, I removed it from the workflow, but you'll need to remove it in the repo settings as a Required check

**Comment by wavded** [comment]
Thx @macrouch !

**Pull request merged**
